---
version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html
    overwrite: true
hooks:
  ApplicationStop:
    - location: ./scripts/ApplicationStop.sh
      timeout:
      runas: root
  BeforeInstall:
    - location: ./scripts/BeforeInstall.sh
      timeout:
      runas: root
  AfterInstall:
    - location: ./scripts/AfterInstall.sh
      timeout:
      runas: root
  ApplicationStart:
    - location: ./scripts/ApplicationStart.sh
      timeout:
      runas: root
